### ISSUE TITLE
Typescript gives error when importing .vue files in main.ts

### ISSUE THREAD

**Issue by VicGarg** [YingLiu4203/TypeScript-Vue-Example#1]
Hello,

Nice way to do things with typescript. I really like this code but i am not able to figure out how can i remove error that i am getting in main.ts file for the following statement.

`import App from './App'`

i am getting red underline and says cannot find module './App'. Can you please help me fix it ?

Also added issue here http://stackoverflow.com/questions/42002394/imoporting-vue-components-in-typescript-file

Thanks,
Vishal Garg

**Comment by YingLiu4203** [comment]
This is fixed in webpack 2 and typescript 2. Check https://vuejs.org/v2/guide/typescript.html
